"""
Entry point: run player simulation on all levels in a folder,
output results to a Markdown report.

Usage:
    python run.py [--levels FOLDER] [--output REPORT.md] [--runs N] [--seed S]
"""

import argparse
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

from config import (
    PLAYER_MIX,
    PLAYER_PROFILES,
    SimulationConfig,
)
from engine import (
    Board,
    LevelMetrics,
    SimulationResult,
    compute_level_metrics,
    compute_percentiles,
    load_level,
    run_simulation_batch,
)


# ═══════════════════════════════════════════════════════════════════════════════
#  Formatting helpers
# ═══════════════════════════════════════════════════════════════════════════════

def ms_to_display(ms: float) -> str:
    """Convert milliseconds to human-readable string."""
    if ms < 1000:
        return f"{ms:.0f}ms"
    secs = ms / 1000
    if secs < 60:
        return f"{secs:.1f}s"
    mins = int(secs // 60)
    remaining = secs - mins * 60
    return f"{mins}m {remaining:.0f}s"


def difficulty_label(score: float) -> str:
    """Map difficulty score to a human label."""
    if score < 0.20:
        return "Easy"
    elif score < 0.35:
        return "Medium"
    elif score < 0.50:
        return "Hard"
    elif score < 0.65:
        return "Very Hard"
    else:
        return "Extreme"


# ═══════════════════════════════════════════════════════════════════════════════
#  Report Generator
# ═══════════════════════════════════════════════════════════════════════════════

def generate_report(
    levels: List[Tuple[Board, LevelMetrics]],
    all_results: Dict[int, Dict[str, List[SimulationResult]]],
    sim_config: SimulationConfig,
) -> str:
    """Generate the full Markdown report."""

    lines: List[str] = []
    L = lines.append

    L("# Arrow Escape — Player Simulation Report")
    L("")
    L(f"> Generated by User Simulator | {time.strftime('%Y-%m-%d %H:%M')}")
    L(f"> Runs per level per profile: **{sim_config.runs_per_level}** | "
      f"Seed: **{sim_config.random_seed}** | "
      f"Percentiles: **{sim_config.output_percentiles}**")
    L("")

    # ── Player Mix ────────────────────────────────────────────────────────
    L("## Player Mix")
    L("")
    L("| Archetype | Weight | Description |")
    L("|-----------|--------|-------------|")
    for key, weight in PLAYER_MIX.items():
        prof = PLAYER_PROFILES[key]
        L(f"| {prof.name} | {weight:.0%} | "
          f"scan={prof.scan_time_per_arrow}ms, "
          f"mistake={prof.mistake_rate:.0%}, "
          f"fatigue={prof.fatigue_factor} |")
    L("")

    # ── Summary Table ─────────────────────────────────────────────────────
    L("## Summary — All Levels")
    L("")
    header = "| Level | Board | Arrows | Density | Difficulty | "
    header += " | ".join(f"P{p}" for p in sim_config.output_percentiles)
    header += " | Weighted Median |"
    L(header)
    sep = "|" + "|".join(["---"] * (7 + len(sim_config.output_percentiles))) + "|"
    L(sep)

    for board, metrics in levels:
        lid = metrics.level_id
        level_results = all_results.get(lid, {})

        # Compute weighted percentiles across all player types
        weighted_times: List[float] = []
        for ptype, weight in PLAYER_MIX.items():
            if ptype in level_results:
                times = [r.total_time_ms for r in level_results[ptype]]
                # Weight by repeating (approximate)
                n_samples = max(1, int(weight * 100))
                for t in times:
                    weighted_times.extend([t] * n_samples)

        pcts = compute_percentiles(weighted_times, sim_config.output_percentiles)
        weighted_median = compute_percentiles(weighted_times, [50]).get(50, 0)

        row = (
            f"| {lid:04d} "
            f"| {board.width}×{board.height} "
            f"| {metrics.total_arrows} "
            f"| {metrics.board_density:.1%} "
            f"| {difficulty_label(metrics.difficulty_score)} ({metrics.difficulty_score:.2f}) "
        )
        for p in sim_config.output_percentiles:
            row += f"| {ms_to_display(pcts.get(p, 0))} "
        row += f"| **{ms_to_display(weighted_median)}** |"
        L(row)
    L("")

    # ── Per-Level Detail ──────────────────────────────────────────────────
    L("---")
    L("")
    L("## Per-Level Breakdown")
    L("")

    for board, metrics in levels:
        lid = metrics.level_id
        level_results = all_results.get(lid, {})

        L(f"### Level {lid:04d} — {board.picture} ({board.width}×{board.height})")
        L("")

        # Static metrics
        L("**Static Metrics:**")
        L("")
        L(f"| Metric | Value |")
        L(f"|--------|-------|")
        L(f"| Total arrows | {metrics.total_arrows} |")
        L(f"| Avg bend count | {metrics.avg_bend_count} |")
        L(f"| Max bend count | {metrics.max_bend_count} |")
        L(f"| Solve depth (greedy iterations) | {metrics.max_depth} |")
        L(f"| Min solvable per iteration | {metrics.min_solvable_per_iteration} |")
        L(f"| Board density | {metrics.board_density:.1%} |")
        L(f"| Avg arrow length | {metrics.path_complexity} cells |")
        L(f"| **Difficulty score** | **{metrics.difficulty_score:.4f}** ({difficulty_label(metrics.difficulty_score)}) |")
        L("")

        # Per-profile results
        L("**Simulated Playtime by Player Type:**")
        L("")
        L("| Player Type | P25 | P50 (Median) | P75 | P90 | Avg Mistakes | Avg Taps |")
        L("|-------------|-----|--------------|-----|-----|-------------|----------|")

        for ptype in PLAYER_PROFILES:
            if ptype not in level_results:
                continue
            results = level_results[ptype]
            times = [r.total_time_ms for r in results]
            mistakes = [r.mistake_count for r in results]
            taps = [r.total_taps for r in results]

            pcts = compute_percentiles(times, [25, 50, 75, 90])
            avg_mistakes = sum(mistakes) / len(mistakes) if mistakes else 0
            avg_taps = sum(taps) / len(taps) if taps else 0

            prof = PLAYER_PROFILES[ptype]
            L(f"| {prof.name} "
              f"| {ms_to_display(pcts[25])} "
              f"| {ms_to_display(pcts[50])} "
              f"| {ms_to_display(pcts[75])} "
              f"| {ms_to_display(pcts[90])} "
              f"| {avg_mistakes:.1f} "
              f"| {avg_taps:.1f} |")

        L("")

        # Weighted estimate
        weighted_times: List[float] = []
        for ptype, weight in PLAYER_MIX.items():
            if ptype in level_results:
                times = [r.total_time_ms for r in level_results[ptype]]
                n_samples = max(1, int(weight * 100))
                for t in times:
                    weighted_times.extend([t] * n_samples)

        if weighted_times:
            wp = compute_percentiles(weighted_times, [25, 50, 75, 90])
            L("**Weighted Player Mix Estimate:**")
            L("")
            L(f"| P25 | P50 | P75 | P90 |")
            L(f"|-----|-----|-----|-----|")
            L(f"| {ms_to_display(wp[25])} | {ms_to_display(wp[50])} "
              f"| {ms_to_display(wp[75])} | {ms_to_display(wp[90])} |")
            L("")

        L("---")
        L("")

    # ── Methodology ───────────────────────────────────────────────────────
    L("## Methodology")
    L("")
    L("This simulation models player behavior through multiple layers:")
    L("")
    L("1. **Viewport Model** — Board divided into camera-sized regions with overlap. "
      "Player pans between regions with configurable timing.")
    L("2. **Eye Model** — Effective FOV smaller than camera viewport. "
      "Player scans with saccades and fixations, with recheck probability.")
    L("3. **Arrow Evaluation** — Head finding time scales with arrow length. "
      "Exit path tracing with block recognition. Miss probability for solvable arrows.")
    L("4. **Batch Tap** — Player taps multiple solvable arrows before panning, "
      "with quick rescans between taps.")
    L("5. **Recursive Unblock** — When stuck, player traces blocking chains "
      "up to configurable depth.")
    L("6. **Fatigue** — Exponential time increase per step (per player type).")
    L("7. **Frustration** — Builds on failed scans, decays on successful taps. "
      "High frustration causes random panning instead of systematic search.")
    L("")
    L("### Limitations")
    L("")
    L("- Parameters are **estimated**, not calibrated from real playtests.")
    L("- No hint system simulation.")
    L("- Color confusion penalty not yet implemented (needs color data in level JSON).")
    L("- Frustration model is simplified (linear buildup).")
    L("")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Arrow Escape Player Simulator")
    parser.add_argument(
        "--levels",
        type=str,
        default=str(
            Path(__file__).parent.parent
            / "Gen_from_image"
            / "level_set"
            / "level_set_13_UA_suport"
            / "2_result_test"
        ),
        help="Path to folder containing level JSON files",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=str(Path(__file__).parent / "simulation_report.md"),
        help="Output Markdown report path",
    )
    parser.add_argument("--runs", type=int, default=100, help="Runs per level per profile")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    # ── Configuration ─────────────────────────────────────────────────────
    sim_config = SimulationConfig(
        runs_per_level=args.runs,
        random_seed=args.seed,
    )

    # ── Load levels ───────────────────────────────────────────────────────
    levels_dir = Path(args.levels)
    if not levels_dir.exists():
        print(f"ERROR: Levels directory not found: {levels_dir}")
        sys.exit(1)

    level_files = sorted(levels_dir.glob("*.json"))
    if not level_files:
        print(f"ERROR: No JSON files found in {levels_dir}")
        sys.exit(1)

    print(f"Found {len(level_files)} level files in {levels_dir}")
    print(f"Running {sim_config.runs_per_level} simulations per level per profile")
    print(f"Player profiles: {list(PLAYER_PROFILES.keys())}")
    print()

    # ── Process each level ────────────────────────────────────────────────
    levels_data: List[Tuple[Board, LevelMetrics]] = []
    all_results: Dict[int, Dict[str, List[SimulationResult]]] = {}

    for lf in level_files:
        board = load_level(str(lf))
        metrics = compute_level_metrics(board)
        levels_data.append((board, metrics))

        print(f"Level {board.level_id:04d} ({board.width}×{board.height}, "
              f"{len(board.arrows)} arrows, "
              f"difficulty={metrics.difficulty_score:.3f} {difficulty_label(metrics.difficulty_score)})")

        level_results: Dict[str, List[SimulationResult]] = {}

        for ptype, profile in PLAYER_PROFILES.items():
            t0 = time.time()
            results = run_simulation_batch(board, profile, sim_config)
            elapsed = time.time() - t0

            times = [r.total_time_ms for r in results]
            median = sorted(times)[len(times) // 2]

            print(f"  {profile.name:20s} -> median {ms_to_display(median):>8s} "
                  f"  ({elapsed:.2f}s compute)")

            level_results[ptype] = results

        all_results[board.level_id] = level_results
        print()

    # ── Generate report ───────────────────────────────────────────────────
    report = generate_report(levels_data, all_results, sim_config)

    output_path = Path(args.output)
    output_path.write_text(report, encoding="utf-8")
    print(f"Report saved to: {output_path}")
    print("Done!")


if __name__ == "__main__":
    main()
